# Practice Assignments Solution

In [1]:
#Importing required libraries

import numpy as np
import pandas as pd

## Operations on an Array

### 1. Write a program to find BMI of the patients whose height and weight is provided in the list given below

Use the lists given below:

list of weights (in kg) weights = [57, 69, 54, 65 ,71, 62, 56]

list of heights (in m)
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

In [2]:
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]

# convert the list to array
weights_array = np.array(weights)

heights_array = np.array(heights)

# formula to calculate BMI

BMI = weights_array/(heights_array**2)
BMI

array([22.54657648, 22.53061224, 19.59645812, 21.46915048, 26.39797739,
       20.9572742 , 23.922423  ])

## Arithmetic Functioning in NumPy

### 1. Replace all odd numbers in array with -2

Use the array given below

arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [3]:
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

#Finding odd numbers in the array and assigning them value -2 by indexing the boolean array we get from arr%2!=0
arr[arr%2!=0] = -2

print(arr)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


### 2. Write a program to calculate the sum of each column

Use the array given below: (or create your own array)

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [4]:
A = np.array([[1, 4, 8], [5, 7, 3], [9, 14, 2]])

A.sum(axis=0)

array([15, 25, 13])

### 3.  Write a code to get the element-wise remainder of an array after division by 8

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [5]:
num = np.array([42, 87, 90, 14, 32, 75, 61, 80, 92])

num%8

array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)

## Concatenation of Array

### 1. Stack two arrays vertically

Use the array given below:

array1 = np.arange(10).reshape(2,-1)

array2 = np.repeat(1, 10).reshape(2,-1)

In [6]:
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)

#Concatenating arrays vertically
np.concatenate([array1, array2], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Splitting

### 1. Write a code to divide the array into three sub-arrays containing an equal number of rows

Use the array given below:

A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [7]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
A = np.array(A)


#Splitting the array into 3 sub-arrays containing two rows each
np.split(A, 3)

[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

### 2.  Write a program to divide the array into two sub-arrays containing an equal number of columns

Use the array given below:

B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [8]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
B = np.array(B)

#Splitting the array into two sub-arrays containing two columns each
np.split(B, 2, axis=1)

[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

## Introduction to Pandas Series and Creating Series

### 1. Create a pandas series having values 4, 7, -5, 3, NAN and their index as d, b, a, c, e

In [9]:
data = [4, 7, -5, 3, np.nan]

index = ['d', 'b', 'a', 'c', 'e']

ser = pd.Series(data = data, index = index)

ser

d    4.0
b    7.0
a   -5.0
c    3.0
e    NaN
dtype: float64

## Manipulating Series

### a. Create a pandas series having values 4, 7, -5, 3, NAN and their index as d, b, a, c, e

### b. Write a code to check for null values from the given series.

In [10]:
data = [4, 7, -5, 3, np.nan]

index = ['d', 'b', 'a', 'c', 'e']

ser = pd.Series(data = data, index = index)

ser

d    4.0
b    7.0
a   -5.0
c    3.0
e    NaN
dtype: float64

In [11]:
ser.notnull()

d     True
b     True
a     True
c     True
e    False
dtype: bool

In [12]:
#Additional code to check the number of non-null values
ser.notnull().sum()

4

### 2. Generate a NumPy array where the values in the array range between 0 to 10. Create a series using the same array.

In [13]:
data1 = np.arange(11)

ser1 = pd.Series(data = data1)

ser1

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int32

## Introduction to Dataframes and Creating Dataframes

### 1. Create a dataframe using list

list1 = ['I', 'Love', 'Data', 'Science']

In [14]:
list1 = ['I', 'Love', 'Data', 'Science']

df = pd.DataFrame(data = list1)

df

0
0        I
1     Love
2     Data
3  Science

### 2. Create a dataframe using dictionary

city_state = {'Delhi': 'Delhi', 'Mumbai': 'Maharashtra', 'Kolkata': 'West Bengal', 'Banglore': 'Karnataka'}

In [15]:
city_state = {'Delhi': 'Delhi', 'Mumbai': 'Maharashtra', 'Kolkata': 'West Bengal', 'Banglore': 'Karnataka'}

df1 = pd.DataFrame(data = [city_state])

df1

Delhi       Mumbai      Kolkata   Banglore
0  Delhi  Maharashtra  West Bengal  Karnataka

## Manipulating the Dataframes

### 1. Write a program to select the rows, where the sales are greater than 60000 for Mumbai location

df_store = pd.DataFrame({'Store': ['A', 'B', 'A', 'C', 'D', 'A', 'D', 'A', 'C', 'B'],

'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Hyderabad', 'Pune',
'Mumbai', 'Pune'],

'Sales': [40000, 45600, 56000, 90000, 89000, 87000, 85000, 78000, 89000, 70000]
})

In [16]:
df_store = pd.DataFrame({'Store': ['A', 'B', 'A', 'C', 'D', 'A', 'D', 'A', 'C', 'B'],

'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Hyderabad', 'Pune', 'Mumbai', 'Pune'],
                         
'Sales': [40000, 45600, 56000, 90000, 89000, 87000, 85000, 78000, 89000, 70000] })

#Using & operator to filter the dataframe using two conditions 
df_store[(df_store['Sales']>60000) & (df_store['Location']=='Mumbai')]

Store Location  Sales
3     C   Mumbai  90000
8     C   Mumbai  89000

### 2. Write a program to replace the ‘Store' column, containing the values 'A', 'B', 'C', and 'D' with 'Store_A', Store_B', 'Store_C' and 'Store_D' respectively

In [17]:
df_store['Store'].replace(['A', 'B', 'C', 'D'], ['Store_A', 'Store_B', 'Store_C', 'Store_D'], inplace=True)

In [18]:
df_store

Store   Location  Sales
0  Store_A     Mumbai  40000
1  Store_B       Pune  45600
2  Store_A  Hyderabad  56000
3  Store_C     Mumbai  90000
4  Store_D       Pune  89000
5  Store_A      Delhi  87000
6  Store_D  Hyderabad  85000
7  Store_A       Pune  78000
8  Store_C     Mumbai  89000
9  Store_B       Pune  70000

## Concatenate

### 1. Concatenate rows of two data frames and assign keys

In [19]:
#Defining two dataframes
df1 = pd.DataFrame({
'ID':[101,102,103,104,105],
'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
'Subject':['Maths','English','Science','German','History']})

df2 = pd.DataFrame(
{'ID':[101,102,103,104,105],
'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
'Subject':['English','Science','Social Science','German','History']})

In [20]:
#Keys can be any string or number
pd.concat([df1, df2], keys = ['df1', 'df2'])

ID    Name         Subject
df1 0  101    Alex           Maths
    1  102     Amy         English
    2  103   Allen         Science
    3  104   Alice          German
    4  105  Ayoung         History
df2 0  101   Billy         English
    1  102   Brian         Science
    2  103    Bran  Social Science
    3  104   Bryce          German
    4  105   Betty         History

### 2. Concatenate the two data frames and clear the existing index 

In [21]:
#Defining two dataframes
df_1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])

df_2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])

In [22]:
#Concatenating dataframes and ignoring the existing indices
pd.concat([df_1, df_2], ignore_index = True)

letter  number
0      a       1
1      b       2
2      c       3
3      d       4

## Merging and Joining a Dataframe

### 1. Merge the given data frames by 'ID' and 'Subject'

In [23]:
#Defining two dataframes
df1 = pd.DataFrame({
   'ID':[101,102,103,104,105],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'Subject':['Maths','English','Science','German','History']})
print(df1)
df2 = pd.DataFrame(
   {'ID':[101,102,103,104,105],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'Subject':['English','Science','Social Science','German','History']})
print(df2)

    ID    Name  Subject
0  101    Alex    Maths
1  102     Amy  English
2  103   Allen  Science
3  104   Alice   German
4  105  Ayoung  History
    ID   Name         Subject
0  101  Billy         English
1  102  Brian         Science
2  103   Bran  Social Science
3  104  Bryce          German
4  105  Betty         History


In [24]:
#Merging two dataframes on columns - ID and Subject
pd.merge(df1, df2, on = ['ID', 'Subject'])

ID  Name_x  Subject Name_y
0  104   Alice   German  Bryce
1  105  Ayoung  History  Betty

### 2. Write a code to JOIN (inner) data1 & data2 as data11

In [25]:
#Defining two dataframes
data1 = pd.DataFrame({'SALARY_YEAR1': ['1000', '2000', '3000', '4000'],
                     'SALARY_YEAR2': ['2000', '4000', '6000', '8000']},
                    index= ['2101', '2102', '2103', '2104'])
   
data2 = pd.DataFrame({'SALARY_YEAR3': ['3000', '6000', '12000', '16000'],
                          'SALARY_YEAR4': ['4000', '8000', '15000', '30000']},
                      index= ['2101', '2106', '2103', '2104'])

In [26]:
#Inner join
data11 = data1.join(data2, how='inner')

data11

SALARY_YEAR1 SALARY_YEAR2 SALARY_YEAR3 SALARY_YEAR4
2101         1000         2000         3000         4000
2103         3000         6000        12000        15000
2104         4000         8000        16000        30000

## Pivot Table 

### 1. Use three columns: Sales, Store and Location from the given dataframe and compute 'Mean Sales' for each store by location

In [27]:
df_store = pd.DataFrame({'Store': ['A', 'B', 'A', 'C', 'D', 'A', 'D', 'A', 'C', 'B'],
'Location': ['Mumbai', 'Pune', 'Hyderabad', 'Mumbai', 'Pune', 'Delhi', 'Hyderabad', 'Pune',
'Mumbai', 'Pune'],
'Sales': [40000, 45600, 56000, 90000, 89000, 87000, 85000, 78000, 89000, 70000]
})

df_store

Store   Location  Sales
0     A     Mumbai  40000
1     B       Pune  45600
2     A  Hyderabad  56000
3     C     Mumbai  90000
4     D       Pune  89000
5     A      Delhi  87000
6     D  Hyderabad  85000
7     A       Pune  78000
8     C     Mumbai  89000
9     B       Pune  70000

In [28]:
pd.pivot_table(df_store, index=['Store','Location'])

Sales
Store Location        
A     Delhi      87000
      Hyderabad  56000
      Mumbai     40000
      Pune       78000
B     Pune       57800
C     Mumbai     89500
D     Hyderabad  85000
      Pune       89000

In [29]:
#OR you can get the output using the following code
pd.pivot_table(data = df_store, values = 'Sales', index = 'Store', columns = 'Location', aggfunc = 'mean')

Location    Delhi  Hyderabad   Mumbai     Pune
Store                                         
A         87000.0    56000.0  40000.0  78000.0
B             NaN        NaN      NaN  57800.0
C             NaN        NaN  89500.0      NaN
D             NaN    85000.0      NaN  89000.0